<a href="https://colab.research.google.com/github/keshavnirwan/Machine-Learning-Models/blob/main/Python_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

In [ ]:
import numpy as np
list=["a","b","c","d"]
list2=[1,2,3,4,]
arr1=np.array(list)
arr2=np.array(list2)
arr1


array(['a', 'b', 'c', 'd'], dtype='<U1')

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2


array([1, 2, 3, 4])

In [ ]:
type(arr2)

numpy.ndarray

# **numpy function**

In [ ]:
import numpy as np
a=np.arange(0,20,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# **linspace**

In [ ]:
import numpy as np
a=np.linspace(0,5)
a

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

# **numpy zeros**

In [ ]:
import numpy as np
a=np.zeros([3,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# **numpy ones**

In [ ]:
import numpy as np
a=np.ones([3,2])
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# array reshape


In [ ]:
import numpy as np
a=np.arange(0,10)
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# **EXPONENTIAL FUNCTION**

In [ ]:
import numpy as np
a=np.exp(2)
a

7.38905609893065

**arithmetic operation**

In [ ]:
l1=[1,2,3,4]
l2=[5,6,7,8]
a=l1+l2
a

[1, 2, 3, 4, 5, 6, 7, 8]

matrices using numpy

In [ ]:
import numpy as np
mat1=np.arange(1,10).reshape(3,3)
mat2=np.arange(10,19).reshape(3,3)
print(mat1)
print(mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


transpose

In [ ]:
import numpy as  np
a=np.arange(1,10).reshape(3,3)
a
(np.transpose(a))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**random number**

In [ ]:
import numpy as np
a=np.random.rand(5,15)
a

array([[0.17168493, 0.17887381, 0.21752527, 0.91589408, 0.82378095,
        0.00373071, 0.28394748, 0.64552869, 0.59927245, 0.32504929,
        0.13329317, 0.88967697, 0.92912969, 0.56496948, 0.64450868],
       [0.96853791, 0.73446925, 0.60279436, 0.18885237, 0.82131168,
        0.51251133, 0.18032921, 0.71073053, 0.96422497, 0.98599065,
        0.02833533, 0.46681109, 0.84749597, 0.32062367, 0.53225488],
       [0.15861851, 0.35766658, 0.20031463, 0.4991971 , 0.9075451 ,
        0.64220118, 0.25329025, 0.26350951, 0.60494644, 0.03595462,
        0.25161487, 0.40947385, 0.32230791, 0.31472751, 0.83296263],
       [0.63394244, 0.52478878, 0.03982582, 0.56216957, 0.93784769,
        0.04717419, 0.78079844, 0.75794567, 0.17547748, 0.58559287,
        0.19575004, 0.85513235, 0.9161677 , 0.88985263, 0.85167085],
       [0.86415006, 0.32346904, 0.21430369, 0.16568809, 0.93962227,
        0.52611675, 0.73545292, 0.27845227, 0.76360244, 0.80781181,
        0.87209755, 0.89951562, 0.28721347, 

**pandas**

In [ ]:
import pandas as pd
import numpy as np
l1=[1,2,3,4,5]
arr=np.array(l1)
a=pd.Series(l1)
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
 import numpy as np
 import pandas as pd
 stud=['a','b','c','d']
 a=pd.DataFrame(stud,columns=['student'])
 a
 gr=['A+','B-','C+',"D+"]
 v=pd.DataFrame({"student":stud,"grades":gr})
 v


student grades
0       a     A+
1       b     B-
2       c     C+
3       d     D+

**loc &iloc**

In [ ]:
import pandas as pd
a=['cust01','cust02','cust03']
b=['ad','fr','gt']
c=['male','female','male']
d=pd.DataFrame({'customer':a,'number':b,"name":c})
d

customer number    name
0   cust01     ad    male
1   cust02     fr  female
2   cust03     gt    male

In [ ]:
import pandas as pd
a=['cust01','cust02','cust03']
b=['ad','fr','gt']
c=['male','female','male']
d=pd.DataFrame({'customer':a,'number':b,"name":c})
d.loc[2][2]

'male'

In [ ]:
import pandas as pd
a=['cust01','cust02','cust03']
b=['ad','fr','gt']
c=['male','female','male']
d=pd.DataFrame({'customer':a,'number':b,"name":c})
d.iloc[[1,2],[0,2]]

customer    name
1   cust02  female
2   cust03    male

In [ ]:
import pandas as pd
c=['custid101','custid102','custid103']
b=['abc','gfh','jhg']
d=['male','female','male']
e=[50,60,70]
df4=pd.DataFrame({'customer':c,"name":b,"gender":d,'rent paid':e})
df4

customer name  gender  rent paid
0  custid101  abc    male         50
1  custid102  gfh  female         60
2  custid103  jhg    male         70

In [ ]:
df4['rent paid']>60



0    False
1    False
2     True
Name: rent paid, dtype: bool

**adding column in dataframe**

In [ ]:
  df4['house']=['small','medium','large']
  df4

customer name  gender  rent paid   house
0  custid101  abc    male         50   small
1  custid102  gfh  female         60  medium
2  custid103  jhg    male         70   large

**deleting row in DataFrame**

In [ ]:
df5=df4.drop('house',axis=1)
df5

customer name  gender  rent paid
0  custid101  abc    male         50
1  custid102  gfh  female         60
2  custid103  jhg    male         70

**concatinating DataFrames**

In [ ]:
import pandas as pd
a=['fwf','fws','gdf','fde']
b=['m','f','m','f']
c=[10000,20000,30000,40000]
d=pd.DataFrame({'Name':a,'Gender':b,'Salary':c})
d

Name Gender  Salary
0  fwf      m   10000
1  fws      f   20000
2  gdf      m   30000
3  fde      f   40000

In [ ]:
import pandas as pd
a2=['fwf','fws','gdf','fde','uyh']
b2=['f','m','f','m','m']
c2=[300,400,200,500,979]
d2=pd.DataFrame({'Name':a2,'Gender':b2,'fees':c2})
d2

Name Gender  fees
0  fwf      f   300
1  fws      m   400
2  gdf      f   200
3  fde      m   500
4  uyh      m   979

In [ ]:
df=pd.concat([d,d2],axis=1)
df

Name Gender   Salary Name Gender  fees
0  fwf      m  10000.0  fwf      f   300
1  fws      f  20000.0  fws      m   400
2  gdf      m  30000.0  gdf      f   200
3  fde      f  40000.0  fde      m   500
4  NaN    NaN      NaN  uyh      m   979

**merge**

In [ ]:
df2=pd.merge(d,d2,how='outer',on='Name')
df2

Name Gender_x   Salary Gender_y  fees
0  fwf        m  10000.0        f   300
1  fws        f  20000.0        m   400
2  gdf        m  30000.0        f   200
3  fde        f  40000.0        m   500
4  uyh      NaN      NaN        m   979

In [ ]:
df3=pd.merge(d,d2,how='inner',on='Name')
df3

Name Gender_x  Salary Gender_y  fees
0  fwf        m   10000        f   300
1  fws        f   20000        m   400
2  gdf        m   30000        f   200
3  fde        f   40000        m   500

In [ ]:
df4=pd.merge(d,d2,how='right',on='Name')
df4

Name Gender_x   Salary Gender_y  fees
0  fwf        m  10000.0        f   300
1  fws        f  20000.0        m   400
2  gdf        m  30000.0        f   200
3  fde        f  40000.0        m   500
4  uyh      NaN      NaN        m   979

join

In [ ]:
import pandas as pd
df5=pd.DataFrame({'q1':[1,2,3],'q2':[4,5,6]},index=['i1','i2','i3'])
df5

q1  q2
i1   1   4
i2   2   5
i3   3   6

In [ ]:
import pandas as pd
df6=pd.DataFrame({'q3':[7,8,9],'q4':[10,11,12]},index=['i1','i2','i3'])
df6

q3  q4
i1   7  10
i2   8  11
i3   9  12

In [ ]:
x df5.join(df6,how='right')

q1  q2  q3  q4
i1   1   4   7  10
i2   2   5   8  11
i3   3   6   9  12

**saving and loading datasets**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
a=["abc",'ghj','jkl','iop','yuio','qwer']
b=[10,15,18,25,28,30]
c=[100,96,95,94,85,89]
df7=pd.DataFrame({'name':a,'rollno':b,'marks':c})
df7

name  rollno  marks
0   abc      10    100
1   ghj      15     96
2   jkl      18     95
3   iop      25     94
4  yuio      28     85
5  qwer      30     89

In [ ]:
df7.to_csv('/content/drive/MyDrive/.csv',index=False)

In [ ]:
path='/content/drive/MyDrive/.csv'
p=pd.read_csv(path)
p

name  rollno  marks
0   abc      10    100
1   ghj      15     96
2   jkl      18     95
3   iop      25     94
4  yuio      28     85
5  qwer      30     89

In [ ]:
p.head()

name  rollno  marks
0   abc      10    100
1   ghj      15     96
2   jkl      18     95
3   iop      25     94
4  yuio      28     85

In [ ]:
p.shape

(6, 3)

**pandas  functions**

In [ ]:
a=["abc",'ghj','jkl','iop','yuio','qwer','ghjk','asdf','rtyu']
b=[10,15,18,25,28,30,34,35,45]
c=[100,96,95,94,85,89,99,93,99]
df8=pd.DataFrame({'name':a,'rollno':b,'marks':c})
df8

name  rollno  marks
0   abc      10    100
1   ghj      15     96
2   jkl      18     95
3   iop      25     94
4  yuio      28     85
5  qwer      30     89
6  ghjk      34     99
7  asdf      35     93
8  rtyu      45     99

In [ ]:
df8.head()

name  rollno  marks
0   abc      10    100
1   ghj      15     96
2   jkl      18     95
3   iop      25     94
4  yuio      28     85

In [ ]:
df8.tail()

name  rollno  marks
4  yuio      28     85
5  qwer      30     89
6  ghjk      34     99
7  asdf      35     93
8  rtyu      45     99

In [ ]:
df8.shape

(9, 3)

In [ ]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    9 non-null      object
 1   rollno  9 non-null      int64 
 2   marks   9 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 344.0+ bytes


In [ ]:
df8['marks'].min()

85

In [ ]:
df8['marks'].max()

100

In [ ]:
df8.value_counts()

name  rollno  marks
abc   10      100      1
asdf  35      93       1
ghj   15      96       1
ghjk  34      99       1
iop   25      94       1
jkl   18      95       1
qwer  30      89       1
rtyu  45      99       1
yuio  28      85       1
dtype: int64

**statistical functions**

In [ ]:
a=["abc",'ghj','jkl','iop','yuio','qwer','ghjk','asdf','rtyu']
b=[10,15,18,25,28,30,34,35,45]
c=[100,99,95,95,85,89,99,95,99]
df9=pd.DataFrame({'name':a,'rollno':b,'marks':c})
df9

name  rollno  marks
0   abc      10    100
1   ghj      15     99
2   jkl      18     95
3   iop      25     95
4  yuio      28     85
5  qwer      30     89
6  ghjk      34     99
7  asdf      35     95
8  rtyu      45     99

In [ ]:
df9['marks'].mean()

95.11111111111111

In [ ]:
df9['marks'].mode()

0    95
1    99
Name: marks, dtype: int64

In [ ]:
df9['marks'].median()

95.0

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline



In [ ]:
a=pd.read_csv('/content/Automobile.csv')
a

name   mpg  cylinders  displacement  horsepower  \
0    chevrolet chevelle malibu  18.0          8         307.0       130.0   
1            buick skylark 320  15.0          8         350.0       165.0   
2           plymouth satellite  18.0          8         318.0       150.0   
3                amc rebel sst  16.0          8         304.0       150.0   
4                  ford torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
393            ford mustang gl  27.0          4         140.0        86.0   
394                  vw pickup  44.0          4          97.0        52.0   
395              dodge rampage  32.0          4         135.0        84.0   
396                ford ranger  28.0          4         120.0        79.0   
397                 chevy s-10  31.0          4         119.0        82.0   

     weight  acceleration  model_year  origin  
0      3504          12.0          70     usa  
1      3693          11.5          70     usa  
2      3436          11.0          70     usa  
3      3433          12.0          70     usa  
4      3449          10.5          70     usa  
..      ...           ...         ...     ...  
393    2790          15.6          82     usa  
394    2130          24.6          82  europe  
395    2295          11.6          82     usa  
396    2625          18.6          82     usa  
397    2720          19.4          82     usa  

[398 rows x 9 columns]

In [ ]:
a.head()

name   mpg  cylinders  displacement  horsepower  \
0  chevrolet chevelle malibu  18.0          8         307.0       130.0   
1          buick skylark 320  15.0          8         350.0       165.0   
2         plymouth satellite  18.0          8         318.0       150.0   
3              amc rebel sst  16.0          8         304.0       150.0   
4                ford torino  17.0          8         302.0       140.0   

   weight  acceleration  model_year origin  
0    3504          12.0          70    usa  
1    3693          11.5          70    usa  
2    3436          11.0          70    usa  
3    3433          12.0          70    usa  
4    3449          10.5          70    usa

In [ ]:
a.shape

(398, 9)

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          398 non-null    object 
 1   mpg           398 non-null    float64
 2   cylinders     398 non-null    int64  
 3   displacement  398 non-null    float64
 4   horsepower    392 non-null    float64
 5   weight        398 non-null    int64  
 6   acceleration  398 non-null    float64
 7   model_year    398 non-null    int64  
 8   origin        398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [ ]:
a.describe(include='all').T

count unique         top freq         mean         std     min  \
name            398    305  ford pinto    6          NaN         NaN     NaN   
mpg           398.0    NaN         NaN  NaN    23.514573    7.815984     9.0   
cylinders     398.0    NaN         NaN  NaN     5.454774    1.701004     3.0   
displacement  398.0    NaN         NaN  NaN   193.425879  104.269838    68.0   
horsepower    392.0    NaN         NaN  NaN   104.469388    38.49116    46.0   
weight        398.0    NaN         NaN  NaN  2970.424623  846.841774  1613.0   
acceleration  398.0    NaN         NaN  NaN     15.56809    2.757689     8.0   
model_year    398.0    NaN         NaN  NaN     76.01005    3.697627    70.0   
origin          398      3         usa  249          NaN         NaN     NaN   

                  25%     50%     75%     max  
name              NaN     NaN     NaN     NaN  
mpg              17.5    23.0    29.0    46.6  
cylinders         4.0     4.0     8.0     8.0  
displacement   104.25   148.5   262.0   455.0  
horsepower       75.0    93.5   126.0   230.0  
weight        2223.75  2803.5  3608.0  5140.0  
acceleration   13.825    15.5  17.175    24.8  
model_year       73.0    76.0    79.0    82.0  
origin            NaN     NaN     NaN     NaN